### All USERs
GET http://localhost:3000/api/safety-brief/usr


### USER by id
GET http://localhost:3000/api/safety-brief/usr?id=2


### Create USER
POST http://localhost:3000/api/safety-brief/usr
Content-Type: application/json

{
    "username": "luiggi",
    "email": "123@123.com",
    "password": "12345678",
    "pic_url": "https://xsgames.co/randomusers/assets/avatars/male/27.jpg"
}


### Delete USER by id
DELETE http://localhost:3000/api/safety-brief/usr/3


### All BRIEFs ordered by title
GET http://localhost:3000/api/safety-brief/brief


### BRIEF by id
GET http://localhost:3000/api/safety-brief/brief?id=7


### Create BRIEF
POST http://localhost:3000/api/safety-brief/brief
Content-Type: application/json

{
    "title": "Thanksgiving",
    "usr_id": 2
}


### Delete BRIEF by id
DELETE http://localhost:3000/api/safety-brief/brief/4


### DONT by dont_id
GET http://localhost:3000/api/safety-brief/dont?id=2


### All DONTs ordered by category
GET http://localhost:3000/api/safety-brief/dont


### All DONTs in a BRIEF by brief_id ordered by category
GET http://localhost:3000/api/safety-brief/dont?briefID=4


### All categories and QTY in DONT table
GET http://localhost:3000/api/safety-brief/dont/cat


### Add x-ammount of random DONTs to BRIEF from categoty
POST http://localhost:3000/api/safety-brief/brief_dont
Content-Type: application/json

{
    "brief_id": 4,
    "cat": "Long Driving Trip",
    "num_donts": 2
}


### Delete DONT from BRIEF by <brief_id/dont_id>
DELETE http://localhost:3000/api/safety-brief/brief_dont/7/12


### All FAVEs for usr_id
GET http://localhost:3000/api/safety-brief/fave?usrID=1


### Add FAVE
POST http://localhost:3000/api/safety-brief/fave
Content-Type: application/json

{
    "usr_id": 1,
    "dont_id": 15
}


### Delete FAVE by <usr_id/dont_id>
DELETE http://localhost:3000/api/safety-brief/fave/1/15
