### All USERs
GET http://localhost:3000/api/safety-brief/usr


### USER by id
GET http://localhost:3000/api/safety-brief/usr?id=2


### All BRIEFs
GET http://localhost:3000/api/safety-brief/brief


### BRIEF by id
GET http://localhost:3000/api/safety-brief/brief?id=2


### All DONTs
GET http://localhost:3000/api/safety-brief/dont


### All DONTs in a BRIEF by brief_id
GET http://localhost:3000/api/safety-brief/dont?briefID=2

